apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-project
spec:
  selector:
    matchLabels:
      app: loan-project
  template:
    metadata:
      labels:
        app: loan-project
    spec:
      containers:
        - name: loan-project
          image: loan-project
          ports:
            - containerPort: 8080