apiVersion: v1
kind: Service
metadata:
  name: loan-project
  namespace: default
  labels:
    app: loan-project
spec:
  selector:
    app: loan-project
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer